apiVersion: v1
kind: Service
metadata: 
  name: docker-k8s-demo
  labels:
    name: docker-k8s-demo
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: docker-k8s-demo
  type: NodePort